### PR TITLE
style: create namespaces for `Piece` and `AliasPiece`

### PR DESCRIPTION
**Pull request by Lioness100**
After and if this is merged, I'll create a PR in `/framework` to add namespaces to `Command`, `Listener`, and `Argument`, and migrate the use of all of the affected interfaces/enums to using the namespace.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]
Sure, tis a nice shortcut

**Comment by Lioness100** [comment]
Oops, I'll fix ci errors by exporting the types in the namespace when I get to my laptop in a bit

**Review by favna — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by Lioness100** [comment]
This might be going overboard, but should any of `Store`, `StoreRegistry`, or `PieceLocation` get namespaces too?

**Review by favna — APPROVED** [review]

**Comment by favna** [comment]
fuck I renamed it because I thougth this was a different PR. Ohwell.. refactor wasn't going to show up in the changelog either.

**Comment by Lioness100** [comment]
Now that I think about it, it might be a bit weird that `Piece` gets a namespace but `Store` doesn't (cmon guys stores have feelings too). It would just be a:

```ts
export namespace Store {
  export type Options<T extends Piece> = StoreOptions<T>;
  export type Logger = StoreLogger;
  // and we could also add:
  export type Registry = StoreRegistry;
  export type RegistryEntries = StoreRegistryEntries;
}
```

**Comment by favna** [comment]
> Now that I think about it, it might be a bit weird that `Piece` gets a namespace but `Store` doesn't (cmon guys stores have feelings too). It would just be a:
> 
> ```ts
> export namespace Store {
>   export type Options<T extends Piece> = StoreOptions<T>;
>   export type Logger = StoreLogger;
>   // and we could also add:
>   export type Registry = StoreRegistry;
>   export type RegistryEntries = StoreRegistryEntries;
> }
> ```

Might as well go all the way yeah

**Comment by Lioness100** [comment]
Very pog. Do you think I should also add `Location` and `LocationJSON` to the `Piece` namespace in the new pr? *Might as well go all the way*

**Comment by favna** [comment]
Sure

**Pull request merged**
